theme:
  name: terminal
  features:
    - footer.prev_next
repo_url: https://github.com/SupaschaiPh/LGor-Public/
site_url: https://supaschaiph.github.io/LGor-Public/
repo_name: LGor-Public
site_name: Lกอ

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - attr_list
  - md_in_html
